src/Entity/SchoolClasses/SchoolLevel.php
<?php

namespace App\Entity\SchoolClasses;

use App\Entity\Subjects\IsTaught;
use App\Repository\SchoolClassesRepositories\SchoolLevelRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: SchoolLevelRepository::class)]
class SchoolLevel
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $name = null;

    #[ORM\Column]
    #[Assert\LessThanOrEqual(value: 3)]
    #[Assert\GreaterThan(value: -1)]
    private ?int $NbDisciplineFacMax = null;

    #[ORM\OneToMany(mappedBy: 'schoolLevel', targetEntity: SchoolClass::class)]
    private Collection $schoolClasses;

    #[ORM\OneToMany(mappedBy: 'schoolLevel', targetEntity: IsTaught::class)]
    private Collection $areTaught;

    public function __construct()
    {
        $this->schoolClasses = new ArrayCollection();
        $this->areTaught = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getNbDisciplineFacMax(): ?int
    {
        return $this->NbDisciplineFacMax;
    }

    /**
     * @param int|null $NbDisciplineFacMax
     * @return SchoolLevel
     */
    public function setNbDisciplineFacMax(?int $NbDisciplineFacMax): self
    {
        $this->NbDisciplineFacMax = $NbDisciplineFacMax;
        return $this;
    }

    /**
     * @return Collection<int, SchoolClass>
     */
    public function getSchoolClasses(): Collection
    {
        return $this->schoolClasses;
    }

    public function addSchoolClass(SchoolClass $schoolClass): self
    {
        if (!$this->schoolClasses->contains($schoolClass)) {
            $this->schoolClasses->add($schoolClass);
            $schoolClass->setSchoolLevel($this);
        }

        return $this;
    }

    public function removeSchoolClass(SchoolClass $schoolClass): self
    {
        if ($this->schoolClasses->removeElement($schoolClass)) {
            // set the owning side to null (unless already changed)
            if ($schoolClass->getSchoolLevel() === $this) {
                $schoolClass->setSchoolLevel(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, IsTaught>
     */
    public function getAreTaught(): Collection
    {
        return $this->areTaught;
    }

    public function addIsTaught(IsTaught $isTaught): self
    {
        if (!$this->areTaught->contains($isTaught)) {
            $this->areTaught->add($isTaught);
            $isTaught->setSchoolLevel($this);
        }

        return $this;
    }

    public function removeIsTaught(IsTaught $isTaught): self
    {
        if ($this->areTaught->removeElement($isTaught)) {
            // set the owning side to null (unless already changed)
            if ($isTaught->getSchoolLevel() === $this) {
                $isTaught->setSchoolLevel(null);
            }
        }

        return $this;
    }


    public function __toString() : string
    {
        return $this->name;
    }

}

src/Form/SchoolLevelType.php
<?php

namespace App\Form;

use App\Entity\SchoolClasses\SchoolLevel;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SchoolLevelType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom du niveau'
            ])
            ->add('NbDisciplineFacMax', IntegerType::class, [
                'label' => 'Nombre maximum de discipline facultative possible.',
                'attr' => [
                    'min' => 0,
                    'max' => 3,
                ]
            ])
            ->add('send', SubmitType::class, [
                'label' => 'Valider'
        ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => SchoolLevel::class,
        ]);
    }
}

src/Controller/SchoolLevelController.php
<?php

namespace App\Controller;

use App\Entity\SchoolClasses\SchoolLevel;
use App\Form\SchoolLevelType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('accueil/niveaux_scolaire', name: 'school_level')]
#[IsGranted('ROLE_SCOLARITE')]
class SchoolLevelController extends AbstractController
{

    #[Route('/ajouter', name:"_add")]
    public function addSchoolLevelAction(EntityManagerInterface $entityManager, Request $request) : Response
    {
        $schoolLevel = (new SchoolLevel());

        $form = $this->createForm(SchoolLevelType::class, $schoolLevel);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            $entityManager->persist($schoolLevel);
            $entityManager->flush();

            $this->addFlash('info', 'Le niveau a été ajouté');
            return $this->redirectToRoute('school_level_list');
        }

        return $this->render('school_level/form-schoolLevel.html.twig', ['form' => $form->createView()]);
    }

    #[Route('/modifier-{schoolLevelId}-{route}', name:"_edit")]
    public function editSchoolLevelAction(string $route, int $schoolLevelId, EntityManagerInterface $entityManager, Request $request) : Response
    {
        $schoolLevel = $entityManager->getRepository(SchoolLevel::class)->find($schoolLevelId);

        $form = $this->createForm(SchoolLevelType::class, $schoolLevel);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            $entityManager->persist($schoolLevel);
            $entityManager->flush();

            $this->addFlash('info', 'Le niveau a été modifié');
            return $this->redirectToRoute($route);
        }

        return $this->render('school_level/form-schoolLevel.html.twig', ['form' => $form->createView()]);
    }

    #[Route('/liste', name:"_list")]
    public function viewAllLevelAction(EntityManagerInterface $entityManager) : Response
    {
        $schoolLevel = $entityManager->getRepository(SchoolLevel::class)->findAll();

        return $this->render('school_level/viewAllSchoolLevel.html.twig', ['levels'=>$schoolLevel]);
    }
}

templates/school_level/form-schoolLevel.html.twig
{% extends 'base.html.twig' %}

{% block container %}
    {{ form_start(form) }}
    {{ form_errors(form) }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-3">
                    {{ form_label(form.name) }}
                    {{ form_widget(form.name) }}

                    {{ form_label(form.NbDisciplineFacMax) }}
                    {{ form_widget(form.NbDisciplineFacMax) }}
                    {{ form_errors(form.NbDisciplineFacMax, { 'attr': {'class': 'form-control'}}) }}

                    {{ form_label(form.send) }}
                    {{ form_widget(form.send, {'attr':{ 'class': 'btn btn-primary'}}) }}
                </div>
            </div>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/school_level/viewAllSchoolLevel.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('table') }}
{% endblock %}

{% block container %}
    <div class="card">
        <div class="card-body">
            {% if is_granted("ROLE_SCOLARITE") %}
                <a class="btn btn-primary" type="button" href="{{ path('school_level_add') }}">Ajouter un Niveau Scolaire</a>
            {% endif %}
            <table class="table table-hover"
                   data-toggle="table"
                   data-sortable="true"
                   data-search="true">
                <thead>
                    <tr>
                        <th scope="col" data-sortable="true">Name</th>
                        <th scope="col" data-sortable="true">Nombre de discipline facultative choisissable Maximum</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                {% for level in levels %}
                    <tr>
                        <td>
                            {{ level.name }}
                        </td>
                        <td>
                            {{ level.nbDisciplineFacMax }}
                        </td>
                        <td>
                            <a class="btn btn-primary" href="{{ path('school_level_edit', {'schoolLevelId': level.id, 'route': app.request.attributes.get('_route')}) }}">Modifier</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}